from typing import Protocol

from app.dto import UserDTO
from app.entities import User


class UserRepositoryProtocol(Protocol):
    def get_all(self, **filters) -> list[User]: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def update(self, user: User) -> None: ...
    def delete(self, user_id: int) -> None: ...
    def create(self, user: UserDTO) -> int: ...
