from typing import Protocol

from app.dto import CreateUserDTO
from app.entities import UserEntity


class UserRepositoryProtocol(Protocol):
    def get_all(self, **filters) -> list[UserEntity]: ...
    def get_by_id(self, user_id: int) -> UserEntity | None: ...
    def get_by_email(self, email: str) -> UserEntity | None: ...
    def update(self, user: UserEntity) -> None: ...
    def delete(self, user_id: int) -> None: ...
    def create(self, user: CreateUserDTO) -> int: ...
