"""unique constraint in installed device for device id

Revision ID: 0c6d94533637
Revises: dbcc4ca70ffd
Create Date: 2026-04-11 12:51:22.132184

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c6d94533637"
down_revision: Union[str, Sequence[str], None] = "dbcc4ca70ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("installed_devices", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_installed_device_device_id", ["device_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("installed_devices", schema=None) as batch_op:
        batch_op.drop_constraint("uq_installed_device_device_id", type_="unique")

    # ### end Alembic commands ###
