"""add length varchar name house tables

Revision ID: 2802224a8cb7
Revises: 0c6d94533637
Create Date: 2026-04-12 14:42:22.464541

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2802224a8cb7"
down_revision: Union[str, Sequence[str], None] = "0c6d94533637"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("houses", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=mysql.VARCHAR(length=12),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("houses", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=50),
            type_=mysql.VARCHAR(length=12),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
