"""create houses-area foreign key

Revision ID: 314d8892805c
Revises: b3ed7e018fbf
Create Date: 2026-03-23 16:44:40.741105

"""

from typing import Sequence, Union

# import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "314d8892805c"
down_revision: Union[str, Sequence[str], None] = "b3ed7e018fbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.create_foreign_key("house_foreign_key", "houses", ["house_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_constraint("house_foreign_key", type_="foreignkey")

    # ### end Alembic commands ###
