"""reorder tables

Revision ID: 5933a92180c1
Revises: c8e767f0f348
Create Date: 2026-03-26 20:21:36.140035

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5933a92180c1"
down_revision: Union[str, Sequence[str], None] = "c8e767f0f348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installed_devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"], ["areas.id"], ondelete="CASCADE", name="fk_areas"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], ondelete="CASCADE", name="fk_device"
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], ondelete="CASCADE", name="fk_house"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE", name="fk_user"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("installed_device")
    with op.batch_alter_table("track_devices", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_track_devices_device_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_track_devices_device_id",
            "installed_devices",
            ["device_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_devices", schema=None) as batch_op:
        batch_op.drop_constraint("fk_track_devices_device_id", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_track_devices_device_id"),
            "devices",
            ["device_id"],
            ["id"],
            ondelete="CASCADE",
        )

    op.create_table(
        "installed_device",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("device_id", sa.INTEGER(), nullable=False),
        sa.Column("house_id", sa.INTEGER(), nullable=False),
        sa.Column("area_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["area_id"], ["areas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["house_id"], ["houses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("installed_devices")
    # ### end Alembic commands ###
