"""change size for password user table for security integrity for encription

Revision ID: b50ce162a8c7
Revises: 2802224a8cb7
Create Date: 2026-04-12 14:50:24.710694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b50ce162a8c7"
down_revision: Union[str, Sequence[str], None] = "2802224a8cb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=mysql.VARCHAR(length=128),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
