"""initial_scheme

Revision ID: dbcc4ca70ffd
Revises:
Create Date: 2026-03-29 18:10:42.800314

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbcc4ca70ffd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_uuid", sa.String(length=64), nullable=False),
        sa.Column("activation_code", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum("LIGHT", "THERMOSTAT", "CAMERA", "DOOR", "MOVEMENT", name="devicetype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activation_code"),
        sa.UniqueConstraint("device_uuid"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_token", sa.String(length=100), nullable=True),
        sa.Column("verification_token_expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "houses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("invitation_validation", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_houses_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "type",
            sa.Enum("living_room", "bedroom", "kitchen", "outside", name="areatype"),
            nullable=False,
        ),
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name="fk_house_in_area", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "house_id", name="name_unique_by_house_id"),
    )
    op.create_table(
        "installed_devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "area_id IS NULL OR house_id IS NOT NULL", name="chkk_area_requires_house"
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name="fk_areas_in_installed_device",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name="fk_device_in_installed_device",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
            name="fk_house_in_installed_device",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_in_installed_device",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ON", "OFF", name="statusdevice"), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["installed_devices.id"],
            name="fk_track_devices_device_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_devices")
    op.drop_table("installed_devices")
    op.drop_table("areas")
    op.drop_table("houses")
    op.drop_table("users")
    op.drop_table("devices")
    # ### end Alembic commands ###
