"""agregar_set_null_to_installed_devices_and_unique_contraint__to_area

Revision ID: df52985f29cd
Revises: 5933a92180c1
Create Date: 2026-03-27 17:33:24.036603

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df52985f29cd"
down_revision: Union[str, Sequence[str], None] = "5933a92180c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "name_unique_by_house_id", ["name", "house_id"]
        )

    with op.batch_alter_table("installed_devices", schema=None) as batch_op:
        batch_op.drop_constraint("fk_areas", type_="foreignkey")
        batch_op.drop_constraint("fk_house", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_areas", "areas", ["area_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_house", "houses", ["house_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("installed_devices", schema=None) as batch_op:
        batch_op.drop_constraint("fk_areas", type_="foreignkey")
        batch_op.drop_constraint("fk_house", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_areas", "areas", ["area_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_house", "houses", ["house_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_constraint("name_unique_by_house_id", type_="unique")

    # ### end Alembic commands ###
