"""se agregó foreign keys

Revision ID: ee37fb51b671
Revises: 0c58489ba625
Create Date: 2026-03-19 21:26:52.157225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee37fb51b671"
down_revision: Union[str, Sequence[str], None] = "0c58489ba625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("device_uuid", sa.String(length=64), nullable=False)
    )
    op.drop_column("devices", "mqtt_password")
    op.drop_column("devices", "mqtt_username")
    op.drop_column("devices", "device_id")
    op.add_column("houses", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "houses",
        "location",
        existing_type=mysql.VARCHAR(length=16),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.create_foreign_key("fk_houses_user_id", "houses", "users", ["user_id"], ["id"])
    op.alter_column(
        "track_devices",
        "device_id",
        existing_type=mysql.VARCHAR(length=64),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        "fk_track_devices_device_id", "track_devices", "devices", ["device_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_track_devices_device_id", "track_devices", type_="foreignkey"
    )
    op.alter_column(
        "track_devices",
        "device_id",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_constraint("fk_houses_user_id", "houses", type_="foreignkey")
    op.alter_column(
        "houses",
        "location",
        existing_type=sa.String(length=50),
        type_=mysql.VARCHAR(length=16),
        existing_nullable=True,
    )
    op.drop_column("houses", "user_id")
    op.add_column(
        "devices", sa.Column("device_id", mysql.VARCHAR(length=64), nullable=False)
    )
    op.add_column(
        "devices", sa.Column("mqtt_username", mysql.VARCHAR(length=64), nullable=False)
    )
    op.add_column(
        "devices", sa.Column("mqtt_password", mysql.VARCHAR(length=64), nullable=False)
    )
    op.drop_column("devices", "device_uuid")
    # ### end Alembic commands ###
