"""5a8d1b2c3f4e add password reset fields to user

Revision ID: fbcaa71c6688
Revises: b50ce162a8c7
Create Date: 2026-04-20 10:34:38.666275

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbcaa71c6688"
down_revision: Union[str, Sequence[str], None] = "b50ce162a8c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_reset_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "password_reset_token_expired_at",
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password_reset_token_expired_at")
        batch_op.drop_column("password_reset_token")
    # ### end Alembic commands ###
